### ISSUE TITLE
Ubuntu 22.04 LTS Support

### ISSUE THREAD

**Issue by f0o** [zextras/tech-doc#166]
What's the stanza on supporting the current Ubuntu LTS?

**Comment by stefanodavid** [comment]
Hi @f0o 
this question is more relevant for our community forum than for the issue tracker, see e.g. https://community.zextras.com/forum/postid/4370/ and following posts.

We currently support only Ubuntu 20.04, support for 22.04 is not yet considered as an option. You can use the forum to ask for help or share your progress with other users.
