### ISSUE TITLE
Inconsistency in the installation documentation

### ISSUE THREAD

**Issue by kfam-marcink** [zextras/tech-doc#365]
On the site: 
**https://docs.zextras.com/carbonio-ce/html/install/roles/role-vs.html**
installation for Ubuntu 20.04 there is no service named videoserver.service - there is instead carbonio-videoserver.service, so the two lines are a bit incorrect.
The same for the:
** https://docs.zextras.com/carbonio-ce/html/install/roles/role-wsc.html **
apt install postgres-client carbonio-message-broker \
carbonio-message-dispatcher carbonio-ws-collaboration-ce \

There is no such package postgres-client, instead there is postgresql-client. The last \ is also not needed.

**Comment by stefanodavid** [comment]
Hi @kfam-marcink thanks for reporting. These issues are fixed in #374 and #375, respectively
