### ISSUE TITLE
Explain how to get a letsencrypt SSL certificate

### ISSUE THREAD

**Issue by dashohoxha** [Zextras/tech-doc#40]
The docs should also explain how to get a letsencrypt certificate:
https://docs.zextras.com/carbonio-ce/html/security.html#deploy-an-ssl-certificate

This blog does explain it:
https://computingforgeeks.com/install-zextras-carbonio-ce-email-suite-on-ubuntu/

However the steps are a bit complex. Carbonio should automate all these steps with a single command or script. It is possible. Maybe an issue should be created on the proper project, for doing this.

**Comment by stefanodavid** [comment]
HI @dashohoxha, 

Let's Encrypt certificates installation is described in our forum: https://community.zextras.com/free-ssl-certificates-for-carbonio-community-edition-using-lets-encrypt-and-certbot/

I can add that our developers are working on improving on certificate management, but I can not give an ETA at this point.

**Comment by dashohoxha** [comment]
I believe that this blog post should be part of the docs. At least you should add a link to it on the docs. Because I believe that LetsEncrypt is the way that 99% of the users are going to use (maybe I am wrong on this).

**Comment by stefanodavid** [comment]
I added the link to the Community article in the existing page about SSL certificates [1]. It will be available with the next release of the documentation. We will rework that section as soon the improvements to the certificate management will be released.

Thanks for your report @dashohoxha 
[1] https://docs.zextras.com/carbonio-ce/html/security.html#deploy-an-ssl-certificate
