### ISSUE TITLE
[TYPO] Typo on Carbonio CE for Directory Replica - Change "root" to "zextras" user

### ISSUE THREAD

**Issue by uclemmer** [zextras/tech-doc#623]
Team,

I just came over this way looking for alternative to upgrade my dated Zimbra environment.  I ran through a guide and did a couple singe server installations over the weekend.  I am currently creating a test environment to see if Carbonio CE will work for my purposes. So far, I am pleased...

While fooling around with a couple things, I found what I believe is typo in the documentation, so I went down the rabbit hole of submitting a small contribution.  I forked the repo, followed the steps, and was about to submit a PR when I thought I might start here with an issue first.  Since I am new to things here, I wanted to make sure that I was indeed on point before I went through all the effort to submit anything official.

I started with a single server installation on Ubuntu 22.04 LTS.

So, here it is:

While following the instructions to create a DS replica on page:

https://docs.zextras.com/carbonio-ce/html/install/roles/role-ds-replica.html

![Screenshot 2024-07-11 201401](https://github.com/user-attachments/assets/edf398dc-0081-4074-acc4-6849bd0b3f5e)

I tried to run the following command as root:

/opt/zextras/libexec/zmldapenablereplica

This yielded the following error:

Error: must be run as the zextras user

![Screenshot 2024-07-15 141029](https://github.com/user-attachments/assets/51443f67-f8ed-4bf6-8162-f1e264fad54b)

Running as the zextras user worked as expected.

If you all do indeed confirm this to be a typo, then I will be happy to submit a PR.  I also found a couple other small typos while following the guide, and would be happy to correct those in other PRs too.

Let me know.  I would be happy to help.

Sincerely,
Uriah

**Comment by fabiofrancescone** [comment]
Hi Uriah,

It just seems to be a typo.
We are happy to receive your PR for correction.
Thank you!

**Comment by uclemmer** [comment]
I just issued a PR.  First time out, so I am hoping I did everything correctly here.  Please advice if I should make any changes or do anything differently next time.  Thanks!

**Comment by uclemmer** [comment]
It looks like the new release 24.7 got rid of directory replica in the CE build.  Is this a mistake?  The above link used to work.

**Comment by larcara** [comment]
> It looks like the new release 24.7 got rid of directory replica in the CE build. Is this a mistake? The above link used to work.

Hi Uriah,

Thank you for your contribution and PR. Regarding your observation, I want to clarify that our original intent was to position the replica feature within the Carbonio documentation.
We believe that directory replication is more relevant to multi-server infrastructure, together with the concept of a redundant and replicated system, which is addressed by the Carbonio product.

We appreciate your understanding and continued support.

Best regards,

Luca, 
Product Owner, Zextras
